version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: calendarreminder_postgres
    restart: always
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  calendarreminder.api:
    image: calendarreminder.api
    build:
      context: .
      dockerfile: CalendarReminder.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5000"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=calendar_db;Username=${POSTGRES_USER:-admin};Password=${POSTGRES_PASSWORD:-secret}"
    ports:
      - "5000:5000"
      - "5001:5001"

volumes:
  pgdata:
