version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: calendarreminder_postgres
    restart: always
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  calendarreminder.api:
    image: calendarreminder.api
    build:
      context: .
      dockerfile: CalendarReminder.Api/Dockerfile
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./CalendarReminder.Api/appsettings.json:/app/appsettings.json

volumes:
  pgdata:
